# Generated by Django 4.2.11 on 2024-03-21 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=200, verbose_name='Código/Nome Filial')),
                ('nome_cliente', models.CharField(max_length=200, verbose_name='Nome do cliente')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=15, null=True, verbose_name='CPF/CNPJ')),
                ('doc_fiscal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número NFe/CFe')),
                ('data_entrada', models.DateTimeField(auto_now=True, verbose_name='Data Entrada')),
                ('data_max_resp', models.DateTimeField(verbose_name='Data Máxima de Resposta')),
                ('data_max_retorno', models.DateTimeField(verbose_name='Data Máxima Para Retorno')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, verbose_name='Codigo Produto Completo')),
                ('descricao', models.CharField(max_length=120, verbose_name='Descrição Produto')),
                ('descricao_df', models.TextField(verbose_name='Descrição do Defeito')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisedf.pedidoanalise')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_status', models.DateTimeField(auto_now=True, verbose_name='Data')),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('em_analise', 'Em analise'), ('aguardando_transporte', 'aguardando transporte')], default='aguardando_transporte', max_length=30, verbose_name='Status')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisedf.produtoanalise')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoAnaliseFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produto/imagens')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisedf.produtoanalise')),
            ],
        ),
    ]
