# Generated by Django 4.2.11 on 2024-05-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisedf', '0003_pedidoanalise_user_produtostatus_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtostatus',
            name='status',
            field=models.CharField(choices=[('recebido', 'Recebido'), ('pedido_em_edição', 'Pedido em Edição'), ('em_analise', 'Em analise'), ('aguardando_transporte', 'aguardando transporte')], default='aguardando_transporte', max_length=30, verbose_name='Status'),
        ),
    ]
