# Generated by Django 4.2.11 on 2024-03-26 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisedf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtostatus',
            options={'verbose_name_plural': 'Produto status'},
        ),
    ]
